using System.Collections.Generic;

namespace PartyNest
{
    internal class Parrot
    {
        public string Name { get; set; }
        public string Path { get; set; }
        public bool IsHD { get; set; }
        public string Tip { get; set; }

        public static IEnumerable<Parrot> Parrots = new List<Parrot>
        {
            new Parrot { Name = "Parrot", Path = "hd/parrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Open-source Parrot", Path = "hd/opensourceparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Middle Parrot", Path = "hd/middleparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Reverse Parrot", Path = "hd/reverseparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Aussie Parrot", Path = "hd/aussieparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Goth Parrot", Path = "hd/gothparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Old Timey Parrot", Path = "oldtimeyparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Bored Parrot", Path = "hd/boredparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Shuffle Parrot", Path = "hd/shuffleparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Shuffle Further Parrot", Path = "shufflefurtherparrot.gif", IsHD = false, Tip = "Combine with Shuffle Parrot for a conga line!", },
            new Parrot { Name = "Conga Line Parrot", Path = "hd/congaparrot.gif", IsHD = true, Tip = "A self sufficient conga line parrot!", },
            new Parrot { Name = "Reverse Conga Line Parrot", Path = "hd/reversecongaparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Party Parrot", Path = "hd/partyparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Sad Parrot", Path = "hd/sadparrot.gif", IsHD = true, Tip = "Parrots are entitled to their full range of emotions.", },
            new Parrot { Name = "Cop Parrot", Path = "hd/copparrot.gif", IsHD = true, Tip = "Not to be confused with Stripper Parrot!", },
            new Parrot { Name = "Fast Parrot", Path = "hd/fastparrot.gif", IsHD = true, Tip = "Now with 50% more party!", },
            new Parrot { Name = "Ultra Fast Parrot", Path = "hd/ultrafastparrot.gif", IsHD = true, Tip = "Now with 150% more party!", },
            new Parrot { Name = "Slow Parrot", Path = "hd/slowparrot.gif", IsHD = true, Tip = "Web 1.0 all over again!", },
            new Parrot { Name = "Slo-mo Parrot", Path = "slomoparrot.gif", IsHD = false, Tip = "Party in slow motion.", },
            new Parrot { Name = "Dad Parrot", Path = "hd/dadparrot.gif", IsHD = true, Tip = "Is totally freaking out.", },
            new Parrot { Name = "Deal With It Parrot", Path = "hd/dealwithitparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Deal With It Now Parrot", Path = "hd/dealwithitnowparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Fiesta Parrot", Path = "fiestaparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Chill Parrot", Path = "chillparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Explody Parrot", Path = "explodyparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Shuffle Party Parrot", Path = "shufflepartyparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Ice-Cream Parrot", Path = "icecreamparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Sassy Parrot", Path = "hd/sassyparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Confused Parrot", Path = "hd/confusedparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Aussie Conga Line Parrot", Path = "hd/aussiecongaparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Aussie Reverse Conga Line Parrot", Path = "hd/aussiereversecongaparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Parrot Wave (1)", Path = "wave1parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (2)", Path = "wave2parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (3)", Path = "wave3parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (4)", Path = "wave4parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (5)", Path = "wave5parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (6)", Path = "wave6parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (7)", Path = "wave7parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (8)", Path = "wave8parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot Wave (9)", Path = "wave9parrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Conga Party Parrot", Path = "hd/congapartyparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Moonwalking Parrot", Path = "hd/moonwalkingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Thumbs Up Parrot", Path = "hd/thumbsupparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Coffee Parrot", Path = "coffeeparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Parrot with mustache", Path = "hd/mustacheparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Christmas Parrot", Path = "hd/christmasparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Sleepy Parrot", Path = "hd/sleepingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Happy Hour Parrot", Path = "hd/beerparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Dark Beer Parrot", Path = "darkbeerparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Blonde Sassy Parrot", Path = "blondesassyparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Blues Clues Parrot", Path = "bluescluesparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Gentleman Parrot", Path = "hd/gentlemanparrot.gif", IsHD = true, Tip = "A true gentleman parrot", },
            new Parrot { Name = "Margarita Parrot", Path = "margaritaparrot.gif", IsHD = false, Tip = "Fiesta Parrot is getting his drink on, margarita style!", },
            new Parrot { Name = "Dreidel Parrot", Path = "dreidelparrot.gif", IsHD = false, Tip = "Happy Hanukkah!", },
            new Parrot { Name = "Harry Potter Parrot", Path = "harrypotterparrot.gif", IsHD = false, Tip = "You're a parrot-wizard Harry!", },
            new Parrot { Name = "Upvote Parrot", Path = "upvoteparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Twins Parrot", Path = "hd/twinsparrot.gif", IsHD = true, Tip = "parrot + parrot = great party!", },
            new Parrot { Name = "Triplets Parrot", Path = "tripletsparrot.gif", IsHD = false, Tip = "parrot + parrot + parrot = magnificent party!!!!", },
            new Parrot { Name = "Stable Parrot", Path = "hd/stableparrot.gif", IsHD = true, Tip = "Gyrostablization Mode Initiated", },
            new Parrot { Name = "Ship It Parrot", Path = "shipitparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Ski Parrot", Path = "skiparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Love Parrot", Path = "loveparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Halal Parrot", Path = "halalparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Wendy's Parrot", Path = "hd/wendyparrot.gif", IsHD = true, Tip = "BACONATOR OR DIE!", },
            new Parrot { Name = "Popcorn Parrot", Path = "hd/popcornparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Donut Parrot", Path = "hd/donutparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Evil Parrot", Path = "hd/evilparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Disco Parrot", Path = "hd/discoparrot.gif", IsHD = true, Tip = "1970s Party Parrot", },
            new Parrot { Name = "Matrix Parrot", Path = "matrixparrot.gif", IsHD = false, Tip = "This Parrot took the Red Pill", },
            new Parrot { Name = "Papal Parrot", Path = "papalparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Stalker Parrot", Path = "stalkerparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Science Parrot", Path = "hd/scienceparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Revolution Parrot", Path = "hd/revolutionparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Fidget Spinner Parrot", Path = "fidgetparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Beret Parrot", Path = "hd/beretparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Taco Parrot", Path = "tacoparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Ryan Gosling Parrot", Path = "ryangoslingparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Lucky Parrot", Path = "luckyparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Birthday Party Parrot", Path = "hd/birthdaypartyparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Jedi Parrot", Path = "hd/jediparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Sith Parrot", Path = "hd/sithparrot.gif", IsHD = true, Tip = "Feel the power of the darkside", },
            new Parrot { Name = "Angry Parrot", Path = "hd/angryparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Invisible Parrot", Path = "hd/invisibleparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Fading Parrot", Path = "fadingparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Rotating Parrot", Path = "rotatingparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Crypto Parrot", Path = "cryptoparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Sushi Parrot", Path = "hd/sushiparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Pumpkin Parrot", Path = "hd/pumpkinparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Angel Parrot", Path = "hd/angelparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Blunt Parrot", Path = "hd/bluntparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Sinterklaas Parrot", Path = "hd/sintparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Pirate Parrot", Path = "hd/pirateparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Ceiling Parrot", Path = "hd/ceilingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Mardi Gras Parrot", Path = "hd/mardigrasparrot.gif", IsHD = true, Tip = "Laissez les bons temps rouler!", },
            new Parrot { Name = "Soviet Parrot", Path = "sovjetparrot.gif", IsHD = false, Tip = "даваи даваи!", },
            new Parrot { Name = "Portal Parrot", Path = "portalparrot.gif", IsHD = false, Tip = "The cake is a lie.", },
            new Parrot { Name = "Hard Hat Parrot", Path = "hd/hardhatparrot.gif", IsHD = true, Tip = "[Under Construction]", },
            new Parrot { Name = "Flying Money Parrot", Path = "hd/flyingmoneyparrot.gif", IsHD = true, Tip = "The money is flying away!", },
            new Parrot { Name = "Portal Parrot (Orange Portal)", Path = "hd/portalorangeparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Portal Parrot (Blue Portal)", Path = "hd/portalblueparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Reverse Portal Parrot (Orange Portal)", Path = "hd/reverseportalorangeparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Reverse Portal Parrot (Blue Portal)", Path = "hd/reverseportalblueparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Bunny Parrot", Path = "hd/bunnyparrot.gif", IsHD = true, Tip = "Real men love bunnies", },
            new Parrot { Name = "Norwegian Blue Parrot", Path = "hd/norwegianblueparrot.gif", IsHD = true, Tip = "Remarkable bird, the Norwegian Blue, idn'it, ay?", },
            new Parrot { Name = "Transparront", Path = "hd/transparront.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Fix Parrot", Path = "fixparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Brazilian Player Parrot", Path = "hd/brazilianplayerparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Brazilian Fan Parrot", Path = "hd/brazilianfanparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Spy Parrot", Path = "hd/spyparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Marshmallow Parrot", Path = "hd/marshmallowparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "White Walker Parrot", Path = "hd/whitewalkerparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Calvinist Parrot", Path = "hd/calvinist_parrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "French Parrot", Path = "hd/frenchparrot.gif", IsHD = true, Tip = "Oulala", },
            new Parrot { Name = "Github Party Parrot", Path = "hd/githubparrot.gif", IsHD = true, Tip = "Github PR Party", },
            new Parrot { Name = "Bootleg Parrot", Path = "hd/bootlegparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Biker Parrot", Path = "hd/bikerparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Inverse Parrot", Path = "hd/inverseparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Ping Pong Parrot", Path = "hd/pingpongparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Laptop Parrot", Path = "hd/laptop_parrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "60fps Parrot", Path = "hd/60fpsparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Red Hat Parrot", Path = "hd/redhatparrot.gif", IsHD = true, Tip = "Soon to be IBM parrot...", },
            new Parrot { Name = "Football Parrot", Path = "hd/footballparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Flower Parrot", Path = "hd/flowerparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Parrot Not Found", Path = "hd/parrotnotfound.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Spinning Parrot", Path = "hd/spinningparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Red Envelope Parrot", Path = "hd/redenvelopeparrot.gif", IsHD = true, Tip = "Happy Lunar New Year!", },
            new Parrot { Name = "Groucho Parrot", Path = "hd/grouchoparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Chico Parrot", Path = "hd/chicoparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Harpo Parrot", Path = "hd/harpoparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Schnitzel Parrot", Path = "schnitzelparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Viking Parrot", Path = "hd/vikingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Dark Mode Parrot", Path = "hd/darkmodeparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Tie Dye Parrot", Path = "hd/tiedyeparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Horizontal Parrot", Path = "hd/horizontalparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Sherlock Parrot", Path = "hd/sherlockholmesparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Tennis Parrot", Path = "hd/tennisparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Original Parrot", Path = "hd/originalparrot.gif", IsHD = true, Tip = "The one and only.", },
            new Parrot { Name = "Boba Parrot", Path = "hd/bobaparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Backwards Parrot", Path = "hd/backwardsparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "RIP Parrot", Path = "ripparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Short Parrot", Path = "hd/shortparrot.gif", IsHD = true, Tip = "Someone get a ladder", },
            new Parrot { Name = "Headset Parrot", Path = "hd/headsetparrot.gif", IsHD = true, Tip = "Hear no evil", },
            new Parrot { Name = "Bouncing Parrot", Path = "hd/bouncingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Levitation Parrot", Path = "hd/levitationparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Vertical Parrot", Path = "hd/verticalparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Database Parrot", Path = "databaseparrot.gif", IsHD = false, Tip = "To sql or not to sql", },
            new Parrot { Name = "PHParrot", Path = "hd/phparrot.gif", IsHD = true, Tip = "if (!$party) { die(); }", },
            new Parrot { Name = "Merged Parrot", Path = "mergedparrot.gif", IsHD = false, Tip = "Celebrating the merge!", },
            new Parrot { Name = "Braveheart Parrot", Path = "braveheartparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Maracas Parrot", Path = "hd/maracasparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Bob Ross Parrot", Path = "bobrossparrot.gif", IsHD = false, Tip = "Happy trees, happy life!", },
            new Parrot { Name = "Yosemite Sam Parrot", Path = "hd/yosemitesamparrot.gif", IsHD = true, Tip = "Now I got you Rabbit!", },
            new Parrot { Name = "Illuminati Parrot", Path = "hd/illuminatiparrot.gif", IsHD = true, Tip = "All Seeing Parrot", },
            new Parrot { Name = "Michael Jackson Parrot", Path = "hd/michaeljacksonparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Picasso Parrot", Path = "hd/picassoparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Heading Parrot", Path = "hd/headingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "InnerSource Parrot", Path = "hd/innersourceparrot.gif", IsHD = true, Tip = "InnerSource-Commons Parrot", },
            new Parrot { Name = "async Parrot", Path = "asyncparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Meld Parrot", Path = "hd/meldparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Doc Parrot", Path = "hd/docparrot.gif", IsHD = true, Tip = "Or any medical professional really...", },
            new Parrot { Name = "Rythmical Parrot", Path = "hd/rythmicalparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Exceptionally Fast Parrot", Path = "exceptionallyfastparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Work from Home Parrot", Path = "hd/wfhparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "COVID-19 Parrot", Path = "hd/covid19parrot.gif", IsHD = true, Tip = "Parrot takes a break from partying to socially distance", },
            new Parrot { Name = "Metal Parrot", Path = "metalparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Wine Parrot", Path = "hd/wineparrot.gif", IsHD = true, Tip = "Parrot and a Pinot", },
            new Parrot { Name = "Hypno Parrot", Path = "hd/hypnoparrot.gif", IsHD = true, Tip = "You are getting sleepy!", },
            new Parrot { Name = "Hypno Parrot Dark", Path = "hd/hypnoparrotdark.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Hypno Parrot Light", Path = "hd/hypnoparrotlight.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Everything Is Fine Parrot", Path = "hd/everythingsfineparrot.gif", IsHD = true, Tip = "It's really not", },
            new Parrot { Name = "Head Banging Parrot", Path = "hd/headbangingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "TP Parrot", Path = "hd/tpparrot.gif", IsHD = true, Tip = "Don't Hoard, ppl", },
            new Parrot { Name = "Stay Home Parrot", Path = "hd/stayhomeparrot.gif", IsHD = true, Tip = "He's in there", },
            new Parrot { Name = "Stay Home Parrot Closer", Path = "hd/stayhomeparrotcloser.gif", IsHD = true, Tip = "See I told you", },
            new Parrot { Name = "Stay Home Parrot Window", Path = "hd/stayhomeparrotwindow.gif", IsHD = true, Tip = "Get off my lawn", },
            new Parrot { Name = "Stay TF Home Parrot", Path = "hd/staytfhomeparrot.gif", IsHD = true, Tip = "Can I help you?", },
            new Parrot { Name = "Ruby Parrot", Path = "hd/rubyparrot.gif", IsHD = true, Tip = "This Parrot surely loves gems", },
            new Parrot { Name = "Moon Parrot", Path = "hd/moonparrot.gif", IsHD = true, Tip = "Parrot and the moon", },
            new Parrot { Name = "Hmm Parrot", Path = "hd/hmmparrot.gif", IsHD = true, Tip = "Hmmmmm...", },
            new Parrot { Name = "Node Parrot", Path = "hd/nodeparrot.gif", IsHD = true, Tip = "party.on(\"end\",e => {die()})", },
            new Parrot { Name = "Hanami Parrot", Path = "hd/hanamiparrot.gif", IsHD = true, Tip = "Very beautiful", },
            new Parrot { Name = "Revert It Parrot", Path = "revertitparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Daft Punk Parrot", Path = "hd/daftpunkparrot.gif", IsHD = true, Tip = "Harder Better Faster Stronger", },
            new Parrot { Name = "Zouk Parrot", Path = "hd/zoukparrot.gif", IsHD = true, Tip = "Parrot turned tropical", },
            new Parrot { Name = "Glimpse Parrot", Path = "hd/glimpseparrot.gif", IsHD = true, Tip = "A glimpse from the wall", },
            new Parrot { Name = "Daily Parrot", Path = "hd/dailyparrot.gif", IsHD = true, Tip = "A parrot to announce daily meetings", },
            new Parrot { Name = "Quad Parrot", Path = "hd/quadparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Dab Parrot", Path = "dabparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Gots some hops", Path = "hd/jumpingparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Jr. Bounce Parrot", Path = "hd/jumpingparrotjr.gif", IsHD = true, Tip = "Aww hey little fella", },
            new Parrot { Name = "151 Pokémon Parrot", Path = "hd/pokeparrot.gif", IsHD = true, Tip = "One Hundred Fifty-One Parrot", },
            new Parrot { Name = "Cake Parrot", Path = "hd/cakeparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Unicorn Parrot", Path = "unicornparrot.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "The Fastest Parrot", Path = "hd/thefastestparrot.gif", IsHD = true, Tip = "Really fast", },
            new Parrot { Name = "Catch ball Left Parrot", Path = "hd/playcatchleftparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Catch ball Right Parrot", Path = "hd/playcatchrightparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Bi Parrot", Path = "hd/biparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Imposter Parrot", Path = "hd/imposterparrot.gif", IsHD = true, Tip = "Looks kinda sus", },
            new Parrot { Name = "Kinda Sus Parrot", Path = "hd/kindasusparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Chef parrot", Path = "chefparrot.gif", IsHD = false, Tip = "Cooking parrot", },
            new Parrot { Name = "Turn Down for Watch", Path = "hd/turndownforwatchparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Pear Parrots", Path = "pear-parrots.gif", IsHD = false, Tip = "", },
            new Parrot { Name = "Tin foil hat Parrot", Path = "hd/tinfoilhatparrot.gif", IsHD = true, Tip = "", },
            new Parrot { Name = "Mate Parrot", Path = "hd/mateparrot.gif", IsHD = true, Tip = "South-american mate fan Parrot", },
            new Parrot { Name = "Ethereum Parrot", Path = "hd/ethparrot.gif", IsHD = true, Tip = "", },
        };
    }
}